server {
    listen 80;

    # Serve os arquivos estáticos do React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Tratamento para rotas do React Router
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para a API
    # Redireciona chamadas de /api/rota para http://api:8000/rota
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy reverso para fotos
    location /fotos/ {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
